#include "Singleton.h"
#include "DataBlockHelper.h"


//定义部分
#define DATABLOCK_BEGIN			DATABLOCK_BEGIN_DEFINE
#define DATABLOCK_PARAM			DATABLOCK_PARAM_DEFINE
#define DATABLOCK_PARAM_STRING	DATABLOCK_PARAM_STRING_DEFINE
#define DATABLOCK_PARAM_STL_SINGLE	DATABLOCK_PARAM_STL_DEFINE_SINGLE
#define DATABLOCK_PARAM_USER	DATABLOCK_PARAM_USER_DEFINE
#define DATABLOCK_END			DATABLOCK_END_DEFINE

#include "DataBlockInclude.h"

#undef DATABLOCK_BEGIN
#undef DATABLOCK_PARAM
#undef DATABLOCK_PARAM_STRING
#undef DATABLOCK_PARAM_STL_SINGLE
#undef DATABLOCK_PARAM_USER
#undef DATABLOCK_END


