#include "DataBlockDefine.h"
//实现部分
#define DATABLOCK_BEGIN			DATABLOCK_BEGIN_IMP
#define DATABLOCK_PARAM			DATABLOCK_PARAM_IMP
#define DATABLOCK_PARAM_STRING	DATABLOCK_PARAM_STRING_IMP
#define DATABLOCK_PARAM_STL_SINGLE		DATABLOCK_PARAM_STL_IMP_SINGLE
#define DATABLOCK_PARAM_USER	DATABLOCK_PARAM_USER_IMP
#define DATABLOCK_END			DATABLOCK_END_IMP

#include "DataBlockInclude.h"

#undef DATABLOCK_BEGIN
#undef DATABLOCK_PARAM
#undef DATABLOCK_PARAM_STRING
#undef DATABLOCK_PARAM_STL_SINGLE
#undef DATABLOCK_PARAM_USER
#undef DATABLOCK_END

						